export const direLocal: string = "http://localhost:3000/"
export const direRailway: string = "https://vanesabackend-production-a947.up.railway.app/"

export const authEndpoint = direLocal + "auth/login"
export const countEndpoint = direLocal + "api/counts"

export const profGetEndpoint = direLocal + "api/profes/private"
export const vetesGetEndpoint = direLocal + "api/vetes/private"
export const missingsGetEndpoint = direLocal + "api/missings"
export const blogGetEndpoint = direLocal + "api/blogs/private"
export const eventGetEndpoint = direLocal + "api/events/private"
export const publicidadGetEndpoint = direLocal + "api/publicidad/private"
export const servGetEndpoint = direLocal + "api/publicidad/private"

export const profPostEndpoint = direLocal + "api/profes/private"
export const vetesPostEndpoint = direLocal + "api/vetes/private"
export const blogPostEndpoint = direLocal + "api/blogs/private"
export const eventPostEndpoint = direLocal + "api/events/private"
export const missingsPostEndpoint = direLocal + "api/missings/private"
export const publiPostEndpoint = direLocal + "api/publicidad/private"
export const servPostEndpoint = direLocal + "api/publicidad/private"


export const profDelEndpoint = direLocal + "api/profes/private"
export const publiDelEndpoint = direLocal + "api/publicidad/private"
export const vetesDelEndpoint = direLocal + "api/vetes/private"
export const blogDelEndpoint = direLocal + "api/blogs/private"
export const eventDelEndpoint = direLocal + "api/events/private"
export const missingsDelEndpoint = direLocal + "api/missings/private"
export const servDelEndpoint = direLocal + "api/missings/private"
